import asyncio
from typing import Any, Iterable

from black.output import err as err

def maybe_install_uvloop() -> None: ...
def cancel(tasks: Iterable[asyncio.Task[Any]]) -> None: ...
def shutdown(loop: asyncio.AbstractEventLoop) -> None: ...
