from typing import List, Pattern

STRING_PREFIX_CHARS: str

def sub_twice(regex: Pattern[str], replacement: str, original: str) -> str: ...
def has_triple_quotes(string: str) -> bool: ...
def lines_with_leading_tabs_expanded(s: str) -> List[str]: ...
def fix_docstring(docstring: str, prefix: str) -> str: ...
def get_string_prefix(string: str) -> str: ...
def assert_is_leaf_string(string: str) -> None: ...
def normalize_string_prefix(s: str, remove_u_prefix: bool = ...) -> str: ...
def normalize_string_quotes(s: str) -> str: ...
