# Stubs for rdflib (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rdflib import util as util
from rdflib.graph import ConjunctiveGraph as ConjunctiveGraph
from rdflib.graph import Dataset as Dataset
from rdflib.graph import Graph as Graph
from rdflib.namespace import OWL as OWL
from rdflib.namespace import RDF as RDF
from rdflib.namespace import RDFS as RDFS
from rdflib.namespace import XSD as XSD
from rdflib.namespace import Namespace as Namespace
from rdflib.term import BNode as BNode
from rdflib.term import Literal as Literal
from rdflib.term import URIRef as URIRef
from rdflib.term import Variable as Variable
