environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install --disable-pip-version-check --user --upgrade pip"

build_script:
  - "%CMD_IN_ENV% python setup.py install"
  # - "%PYTHON%\\python.exe -m pip install wheel"

test_script:
  - "%CMD_IN_ENV% python setup.py test"