[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "schema-salad"
description = "Schema Annotations for Linked Avro Data (SALAD)"
readme = "README.rst"
license = "Apache-2.0"
license-file = "LICENSE.txt"
requires-python = ">=3.10"
authors = [
  { name = "Common workflow language working group", email = "common-workflow-language@googlegroups.com" },
]
classifiers = [
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: POSIX",
  "Operating System :: MacOS :: MacOS X",
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
dependencies = [
  "requests >= 1.0",
  "ruamel.yaml >= 0.17.6, < 0.20",
  "rdflib >= 4.2.2, < 8.0.0",
  "mistune>=3.3.0,<3.4",
  "CacheControl[filecache] >= 0.13.1, < 0.15",
  "mypy_extensions",
  "rich-argparse",
]
dynamic = ["version"]

[project.optional-dependencies]
mypy = [
  "mypy==2.4.0",
  "black>=19.10b0,<26.4",
  "types-requests",
  "types-dataclasses",
  "CacheControl[filecache] >= 0.14.0, < 0.15",
]
docs = [
  "sphinx >= 2.2",
  "sphinx-rtd-theme >= 1",
  "pytest < 10",
  "sphinx-autoapi",
  "sphinx-autodoc-typehints",
  "sphinxcontrib-autoprogram",
]
pycodegen = ["black"]
testing = [
  "pytest >= 6.2, < 9.1",
  "pytest-cov",
  "pytest-xdist",
  "mistune >= 3.1.4",
]

[project.scripts]
schema-salad-tool = "schema_salad.main:main"
schema-salad-doc = "schema_salad.makedoc:main"

[project.urls]
Documentation = "https://schema-salad.readthedocs.io/"
Homepage = "https://www.commonwl.org"
Changelog = "https://github.com/common-workflow-language/schema_salad/releases"
Repository = "https://github.com/common-workflow-language/schema_salad/"
Issues = "https://github.com/common-workflow-language/schema_salad/issues"
"Related Tools" = "https://www.commonwl.org/tools/"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/schema_salad/_version.py"

[tool.hatch.build.targets.sdist]
only-include = [
  "Makefile",
  "LICENSE.txt",
  "mypy.ini",
  "mypy-requirements.txt",
  "CONTRIBUTING.md",
  ".coveragerc",
  "src/schema_salad",
  "docs",
  "lint-requirements.txt",
  "mypy-stubs",
  "README.rst",
  "tox.ini",
]
exclude = ["docs/_build/", "docs/autoapi/"]

[tool.hatch.build.targets.wheel.hooks.mypyc]
enable-by-default = false
dependencies = ["hatch-mypyc"]
require-runtime-dependencies = true
require-runtime-features = ["mypy"]
mypy-args = ["--verbose"]
exclude = [
  "/src/schema_salad/exceptions.py", # leads to memory leaks
  "/src/schema_salad/fetcher.py",    # to allow subclassing {Default,}Fetcher 
  "/src/schema_salad/metaschema.py", # "Multiple inheritance is not supported"
  "/src/schema_salad/python_codegen_support.py",
  "/src/schema_salad/runtime.py",    # "interpreted classes cannot inherit from compiled"
  "/src/schema_salad/tests/**",      # don't compile the tests
]

[build.targets.wheel.hooks.mypyc.options]
verbose = true

[tool.cibuildwheel]
test-command = "python -m pytest -n auto -k 'not (test_load_by_yaml_metaschema)' --junitxml={project}/test-results/junit_$(python -V | awk '{print $2}')_${AUDITWHEEL_PLAT}.xml --pyargs schema_salad"
test-requires = "-r test-requirements.txt"
test-extras = "pycodegen"
build-verbosity = 1
environment = { HATCH_BUILD_HOOKS_ENABLE = "1", MYPYPATH = "$(pwd)/mypy-stubs", CCACHE_SLOPPINESS = "include_file_ctime,include_file_mtime,locale,time_macros", CCACHE_NOHASHDIR = "true" }

[tool.cibuildwheel.linux]
before-all = "apk add ccache || yum install -y ccache || dnf --nogpg -y install https://www.rpmfind.net/linux/opensuse/ports/riscv/tumbleweed/repo/oss/riscv64/ccache-4.14-1.1.riscv64.rpm https://www.rpmfind.net/linux/opensuse/ports/riscv/tumbleweed/repo/oss/riscv64/libcpp-httplib0_49-0.49.0-4.1.riscv64.rpm https://www.rpmfind.net/linux/opensuse/ports/riscv/tumbleweed/repo/oss/riscv64/libfmt12-12.1.0-1.1.riscv64.rpm https://www.rpmfind.net/linux/opensuse/ports/riscv/tumbleweed/repo/oss/riscv64/libhiredis1_3_0-1.3.0-1.1.riscv64.rpm https://www.rpmfind.net/linux/opensuse/ports/riscv/tumbleweed/repo/oss/riscv64/libxxhash0-0.8.4-4.1.riscv64.rpm || apt-get install -y --no-install-recommends ccache"

[tool.cibuildwheel.pyodide]
test-command = "python -m pytest -n 0 -k 'not (test_load_by_yaml_metaschema)' --junitxml={project}/test-results/junit_$(python -V | awk '{print $2}')_${AUDITWHEEL_PLAT}.xml --pyargs schema_salad"
# "-n 0", no support for multiprocessing under pyodide/emscripten

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.pytest.ini_options]
addopts = "-n auto --dist=loadscope --pyargs schema_salad.tests"
pythonpath = [
  "src"
]

[tool.isort]
profile = "black"
