# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '8.3.20220909144502.dev0+g774157d.d20220910'
__version_tuple__ = version_tuple = (8, 3, 20220909144502, 'dev0', 'g774157d.d20220910')
