import abc
from abc import ABCMeta, abstractmethod
from collections.abc import Callable, Iterable
from re import Match
from typing import Any

from ..block_parser import BlockParser as BlockParser
from ..core import BlockState as BlockState
from ..markdown import Markdown as Markdown

class DirectiveParser(ABCMeta, metaclass=abc.ABCMeta):
    name: str
    @staticmethod
    @abstractmethod
    def parse_type(m: Match[str]) -> str: ...
    @staticmethod
    @abstractmethod
    def parse_title(m: Match[str]) -> str: ...
    @staticmethod
    @abstractmethod
    def parse_content(m: Match[str]) -> str: ...
    @classmethod
    def parse_tokens(
        cls, block: BlockParser, text: str, state: BlockState
    ) -> Iterable[dict[str, Any]]: ...
    @staticmethod
    def parse_options(m: Match[str]) -> list[tuple[str, str]]: ...

class BaseDirective(metaclass=ABCMeta):
    parser: type[DirectiveParser]
    directive_pattern: str | None
    def __init__(self, plugins: list["DirectivePlugin"]) -> None: ...
    def register(
        self,
        name: str,
        fn: Callable[[BlockParser, Match[str], BlockState], dict[str, Any] | list[dict[str, Any]]],
    ) -> None: ...
    def parse_method(
        self, block: BlockParser, m: Match[str], state: BlockState
    ) -> dict[str, Any] | list[dict[str, Any]]: ...
    @abstractmethod
    def parse_directive(
        self, block: BlockParser, m: Match[str], state: BlockState
    ) -> int | None: ...
    def register_block_parser(self, md: Markdown, before: str | None = None) -> None: ...
    def __call__(self, markdown: Markdown) -> None: ...

class DirectivePlugin:
    parser: type[DirectiveParser]
    def __init__(self) -> None: ...
    def parse_options(self, m: Match[str]) -> list[tuple[str, str]]: ...
    def parse_type(self, m: Match[str]) -> str: ...
    def parse_title(self, m: Match[str]) -> str: ...
    def parse_content(self, m: Match[str]) -> str: ...
    def parse_tokens(
        self, block: BlockParser, text: str, state: BlockState
    ) -> Iterable[dict[str, Any]]: ...
    def parse(
        self, block: BlockParser, m: Match[str], state: BlockState
    ) -> dict[str, Any] | list[dict[str, Any]]: ...
    def __call__(self, directive: BaseDirective, md: Markdown) -> None: ...
