# Stubs for rdflib.parser (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from io import StringIO as BytesIO
from typing import Any

class Parser:
    def __init__(self): ...
    def parse(self, source, sink): ...
